### ISSUE TITLE
GenomicDistributions plotGCContent issue

### ISSUE THREAD

**Issue by joseverdezoto** [databio/bedstat#1]
https://github.com/databio/bedstat/blob/42e76d5da21c3623969d701d977cbf690eece5b3/tools/regionstat.R#L58

I submitted a subset of the LOLACore database to bedstat but the pipeline execution is halted halfway when reading the regionstat.R script. The pipeline log.md for each sample shows the following error:

**Error in as.data.frame(list(gc = gcvec)) : object 'gcvec' not found
Calls: doitall -> plotGCContent -> as.data.frame**

**Comment by nsheff** [comment]
Did you comment out line 57? 

Are you using the dev version of GenomicDistributions?

**Comment by joseverdezoto** [comment]
- I commented out lines 58 and 59 since I assumed the issue had to do with the **plotGCContent** function and not the **gcvec** object itself. 
- Also, I think I might have installed the master branch of Genomic distributions. If I want to install the **dev** version, should I clone that branch into my working directory?

**Comment by joseverdezoto** [comment]
I just looked at the dev branch code for **plotGCContent** and looks like the typo in the function definition was fixed. I think the pipeline should run well once I download the dev version of Genomic distributions.
