### ISSUE TITLE
elastic error when loading data

### ISSUE THREAD

**Issue by nsheff** [databio/bedstat#11]
Related to #8. I can get elastic running, but it's saying this:

[2019-10-24T19:19:43,521][WARN ][o.e.c.r.a.DiskThresholdMonitor] [zglgMLr] flood stage disk watermark [95%] exceeded on [zglgMLr9SxW_vHYqPURTJg][zglgMLr][/usr/share/elasticsearch/data/nodes/0] free: 1tb[2.3%], all indices on this node will be marked read-only

could that be preventing the pipeline from sticking data into elastic?

**Comment by nsheff** [comment]
yeah, when I try to put it in, I get this error: 

AuthorizationException(403, 'cluster_block_exception', 'blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];')

**Comment by nsheff** [comment]
How can I turn off  cluster.routing.allocation.disk.threshold_enabled

https://www.elastic.co/guide/en/elasticsearch/reference/current/disk-allocator.html

**Comment by oddodaoddo** [comment]
Hmm. To be honest, I have not run into this before. Let me re-run my elastic docker stuff and see what gives. I develop against a real elasticsearch instance on one of my servers at home ;).

**Comment by nsheff** [comment]
I got it to work by just completely deleting the elastic database and starting again.

maybe related to: https://discuss.elastic.co/t/cluster-block-exception-reason-blocked-by-forbidden-12-index-read-only-allow-delete-api/162449

**Comment by oddodaoddo** [comment]
Cool, saves me time to look into this :).
