### ISSUE TITLE
files are not getting inserted into elastic

### ISSUE THREAD

**Issue by nsheff** [databio/bedstat#12]
Related to #11 

I finally got elastic running -- but bedstat does not put any data in it.

Bedstat runs correctly, and no errors are given. In kibana I can see an index called "bedstat_bedfiles"

But it is empty and running the pipeline doesn't change it.

```
 ## [2 of 2773] /home/nsheff/code/bedstat/LOLACore/hg38/encode_tfbs/regions/wgEncodeAwgTfbsBroadDnd41Ezh239875UniPk.narrowPeak (bedstat)
Submission settings lack memory specification
Writing script to /home/nsheff/code/bedstat/output/submission/bedstat_/home/nsheff/code/bedstat/LOLACore/hg38/encode_tfbs/regions/wgEncodeAwgTfbsBroadDnd41Ezh239875UniPk.narrowPeak.sub
Job script (n=1; 0.00 Gb): output/submission/bedstat_/home/nsheff/code/bedstat/LOLACore/hg38/encode_tfbs/regions/wgEncodeAwgTfbsBroadDnd41Ezh239875UniPk.narrowPeak.sub
Compute node: puma
Start time: 2019-10-24 15:41:57
### Pipeline run code and environment:

*              Command:  `pipeline/bedstat.py --bedfile /home/nsheff/code/bedstat/LOLACore/hg38/encode_tfbs/regions/wgEncodeAwgTfbsBroadDnd41Ezh239875UniPk.narrowPeak --genome hg38 -O output/results_pipeline -R`
*         Compute host:  puma
*          Working dir:  /home/nsheff/code/bedstat
*            Outfolder:  /home/nsheff/code/bedstat/output/results_pipeline/wgEncodeAwgTfbsBroadDnd41Ezh239875UniPk/
*  Pipeline started at:   (10-24 15:42:00) elapsed: 3.0 _TIME_

### Version log:

*       Python version:  3.5.2
*          Pypiper dir:  `/home/nsheff/.local/lib/python3.5/site-packages/pypiper`
*      Pypiper version:  0.12.1
*         Pipeline dir:  `/home/nsheff/code/bedstat/pipeline`
*     Pipeline version:  None
*        Pipeline hash:  7c4973148eee59e1887a7b4961a4c049ef1409aa
*      Pipeline branch:  * dev
*        Pipeline date:  2019-10-23 08:31:24 -0400
*        Pipeline diff:  1 file changed, 2 insertions(+), 1 deletion(-)

### Arguments passed to pipeline:

*            `bedfile`:  `/home/nsheff/code/bedstat/LOLACore/hg38/encode_tfbs/regions/wgEncodeAwgTfbsBroadDnd41Ezh239875UniPk.narrowPeak`
*        `config_file`:  `bedstat.yaml`
*              `cores`:  `1`
*              `dirty`:  `False`
*       `force_follow`:  `False`
*    `genome_assembly`:  `hg38`
*              `input`:  `None`
*             `input2`:  `None`
*             `logdev`:  `False`
*                `mem`:  `4000`
*          `new_start`:  `False`
*         `nodbcommit`:  `False`
*      `output_parent`:  `output/results_pipeline`
*            `recover`:  `True`
*        `sample_name`:  `None`
*             `silent`:  `False`
*   `single_or_paired`:  `single`
*           `testmode`:  `False`
*          `verbosity`:  `None`

----------------------------------------

Target to produce: `/home/nsheff/code/bedstat/output/results_pipeline/wgEncodeAwgTfbsBroadDnd41Ezh239875UniPk/wgEncodeAwgTfbsBroadDnd41Ezh239875UniPk.narrowPeak`  

> `Rscript tools/regionstat.R --bedfile=/home/nsheff/code/bedstat/LOLACore/hg38/encode_tfbs/regions/wgEncodeAwgTfbsBroadDnd41Ezh239875UniPk.narrowPeak --fileid=wgEncodeAwgTfbsBroadDnd41Ezh239875UniPk --outputfolder=/home/nsheff/code/bedstat/output/results_pipeline/wgEncodeAwgTfbsBroadDnd41Ezh239875UniPk --genome=hg38` (32631)
<pre>
Loading required package: GenomicRanges
Loading required package: stats4
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colMeans,
    colnames, colSums, dirname, do.call, duplicated, eval, evalq,
    Filter, Find, get, grep, grepl, intersect, is.unsorted, lapply,
    Map, mapply, match, mget, order, paste, pmax, pmax.int, pmin,
    pmin.int, Position, rank, rbind, Reduce, rowMeans, rownames,
    rowSums, sapply, setdiff, sort, table, tapply, union, unique,
    unsplit, which, which.max, which.min

Loading required package: S4Vectors

Attaching package: ‘S4Vectors’

The following object is masked from ‘package:base’:

    expand.grid

Loading required package: IRanges
Loading required package: GenomeInfoDb
Registered S3 methods overwritten by 'ggplot2':
  method         from 
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang
Saving 7 x 7 in image
BSAggregate: Calculating sizes. You can speed this up by supplying a regionsGRL.length vector...Done counting regionsGRL lengths.
Finding overlaps...
Setting regionIDs...
jExpr: .N
Combining...
Saving 7 x 7 in image
Loading required namespace: BSgenome.Hsapiens.UCSC.hg38.masked
Saving 7 x 7 in image
promoterCore :	found 227
promoterProx :	found 241
exon :	found 553
intron :	found 421
Saving 7 x 7 in image
</pre>
Command completed. Elapsed time: 0:00:13. Running peak memory: 0.02GB.  
  PID: 32631;	Command: Rscript;	Return code: 0;	Memory used: 0.02GB


### Pipeline completed. Epilogue
*        Elapsed time (this run):  0:00:17
*  Total elapsed time (all runs):  0:00:13
*         Peak memory (this run):  0.0197 GB
*        Pipeline completed time: 2019-10-24 15:42:13

Looper finished
Samples valid for job generation: 2 of 2
Successful samples: 2 of 2
Commands submitted: 2 of 2
Jobs submitted: 2
```

**Comment by nsheff** [comment]
perhaps you can put some more output into the pipeline to confirm when something is successfully inserted or give other information?

**Comment by oddodaoddo** [comment]
I spent a few hours today trying to replicate this problem and I could not. I have changed the code (in dev) to raise an exception if there is a problem committing the json into elastic (instead of just printing the exception on the screen).

I am assuming that you are running elasticsearch in a docker container and running the bedstat code as is on the machine (not from another docker container).

Have you installed the correct version of the elasticsearch python client? The instructions I have for bedstat ask for elasticsearch server version 6.5.4 so the python client has to match this (as per requirements.txt in bedstat folder). If you have installed elasticsearch client via pip but not using my requirements.txt - it pulls in the client for ES server version 7 and above - which may cause odd behaviors when used with ES 6.5.4. 

What does 
```
pip list | grep elastic
```
say?

Can you run the following on your command line and paste the output (after running the bedstat looper code)?
```
curl -X GET 'http://localhost:9200/bedstat_bedfiles/_search'
```

Thanks!

**Comment by oddodaoddo** [comment]
I have also added the following switches to the pipeline code:

* --nodbcommit - if one wants to just produce files and not commit to a database backend
* --dbhost=\<some host or IP\> - if --nodbcommit is not passed in, then --dbhost is required - it points the code to a particular IP or resolvable name to be used.

**Comment by nsheff** [comment]
Thanks for the input. I'll look into it when I'm back at work.

> The instructions I have for bedstat ask for elasticsearch server version 6.5.4 so the python client has to match this.  If you have installed elasticsearch client via pip but not using my requirements.txt - it pulls in the client for ES server version 7 and above - which may cause odd behaviors when used with ES 6.5.4. 

I definitely installed it via pip and not via your requirements.txt file, so that could be the issue! Sorry that was not clear to me. We should add install instructions to the README if that's important.

> I have also added the following switches to the pipeline code

Those look great, thanks!

**Comment by nsheff** [comment]
Also, why are we not using elastic 7 all around?

**Comment by oddodaoddo** [comment]
I am not sure ;) - we probably should. I am working on isolating/blackboxing the database code this weekend. After that is done things will be more flexible. But yes, I agree, we should probably upgrade to latest versions of elastic.

**Comment by oddodaoddo** [comment]
I guess one of the reason why we stuck to 6.5.4 is because I wanted to keep the same versions around since the episb-provider. I figured we might want to "mix" the databases from that project as well. But in reality, these are easy problems to solve, no need to stick to older versions.

**Comment by oddodaoddo** [comment]
@nsheff : I have updated the code and the instructions (in dev branch) to run the latest elastic and there is a small code fix that should do the trick with elastic. Do install elasticsearch-dsl and run the elastic container  as per instructions in README.md and let me know if that worked. Thanks!
