### ISSUE TITLE
Decide on proper/unique naming scheme for samples in database

### ISSUE THREAD

**Issue by oddodaoddo** [databio/bedstat#14]
Problem: currently we decide the "id" of a sample when committed to database (or when producing bedstat pipeline output/results_pipeline/\<id\> by simply taking the name of the bed file and throwing away the extension. For example /path/to/LOLA/hg38/cistrome_cistrome/regions/3.bed gives us an id "3". However, any other unrelated sample in a separate run of bedstat can also be named /path/to/somewhere/else/3.bed and will produce another entry with id of "3". This new entry will then simply overwrite the old one.

We need a naming scheme that is relatively unique but not unfriendly. Using UUIDs would be unique (this is what we did in episb-provider) but maybe unfriendly? We could try inferring and concocting names like cistrome_cistrome_3 but that may fail if someone is providing samples where such inference may not be possible. @nsheff any input is welcome! :smiley:

**Comment by nsheff** [comment]
For now I suggest:

1. use the md5 checksum of the file as a unique identifier
2. use the filename (as you're doing) as a non-unique display name

**Comment by stolarczyk** [comment]
resolved
