### ISSUE TITLE
dbhost pipeline argument producing an error 

### ISSUE THREAD

**Issue by joseverdezoto** [databio/bedstat#15]
When I try to run the bedstat pipeline on some samples, I keep coming across the error: 
`bedstat.py: error: the following arguments are required: --dbhost`

I looked at the `bedstat.py` script and it looks like this argument should default to `'localhost'`?

**Comment by nsheff** [comment]
yes; it should point to wherever your elastic db is running. default should be localhost.

**Comment by joseverdezoto** [comment]
It worked by providing the argument when I ran looper. Not really sure why it didn't set it to `localhost` by default.
