### ISSUE TITLE
BED file metadata inclusion in JSON document?

### ISSUE THREAD

**Issue by joseverdezoto** [databio/bedstat#16]
Currently `bedstat` produces a JSON document with the `bedfile` id, path and stats calculated by `GenomicDistributions`. Is it a good idea to include the `bedfile` metadata (cell type, genome, description, protocol, data source etc) in the JSON doc?. That way `bedbuncher` could access those key:value mappings to construct a more elaborate `bedset` PEP (currently it just encompasses sample name and file path).

**Comment by nsheff** [comment]
yes, we must do this.

Actually it looks like it's already handled, partially:

See:

https://github.com/databio/bedstat/blob/ad714a3176ba623ccf5668c0d1b0ae9c69d009d6/pipeline/bedstat.py#L25-L26

**Comment by nsheff** [comment]
you might just need to add "--sample-yaml: yaml_file" in the pipeline_interface.yaml file and it will work.

**Comment by stolarczyk** [comment]
Yes, but I just used to just take this argument and not do anything about it... until few minutes ago (I've just implemented this functionality) 4da49be9c4c24e2b81ba02dae4f12429c163445e

**Comment by joseverdezoto** [comment]
Right, we just talked about it but I still need to make sure we're getting all the attributes we need for the `bedset` PEP.

**Comment by nsheff** [comment]
@joseverdezoto can you update on the status of this?

**Comment by joseverdezoto** [comment]
So this was taken care of a few weeks ago. `bedstat` now uses the `sample yaml` file produced by `looper` to add metadata into the JSON document used by `bedbuncher`.

@stolarczyk can you confirm we'll be able to do this with the newest version of `looper`?
