### ISSUE TITLE
Maybe the `genome` should become a separate DB column?

### ISSUE THREAD

**Issue by xuebingjie1990** [databio/bedstat#28]
Maybe the `genome` should become a separate DB column? 

`other` can include any metadata and is not subject to content validation in pipestat and we _rely_ on `genome` being included in `other` here.

_Originally posted by @stolarczyk in https://github.com/databio/bedbuncher/pull/26#discussion_r580358221_

**Comment by stolarczyk** [comment]
It will need to be added to a schema in bbconf first
