### ISSUE TITLE
first index row lost by process_LOLA.py

### ISSUE THREAD

**Issue by stolarczyk** [databio/bedstat#3]
if `process_LOLA.py` is executed with TSV-formatted `index.txt` the first row is lost. This is due to `next` method call on `DictReader` prior to the reading:

https://github.com/databio/bedstat/blob/42e76d5da21c3623969d701d977cbf690eece5b3/scripts/process_LOLA.py#L28

**Comment by oddodaoddo** [comment]
I am skipping the first row of an index.txt file (after it has already been read in by the csv module) because the first row is assumed to be a tab delimited or a comma delimited header row. Since the file has already been read-in, this means that there is already a way to address the columns via name (obtained from the header of the file)  - we do not need the header for anything else.

**Comment by stolarczyk** [comment]
Yes, I agree. But this is what I was getting at here:

- `process_LOLA.py` with TSV input:
```
[mjs5kd@udc-ba36-36 bedstat](master): python3 scripts/process_LOLA.py --genome hg38 --lola_loc ~/tests/data/tsv
sample_name,celltype,protocol,genome
/home/mjs5kd/tests/data/tsv/hg38/test_data_tsv/regions/b.bed,b,bedstat,hg38
/home/mjs5kd/tests/data/tsv/hg38/test_data_tsv/regions/c.bed,c,bedstat,hg38
```
- the input file:
```
[mjs5kd@udc-ba36-36 bedstat](master): cat ~/tests/data/tsv/hg38/test_data_tsv/index.txt
filename	cellType	treatment  	description
a.bed	a	None	first  cell line
b.bed	b	None	second  cell line
c.bed	c	EWS-FLI1	test
```

The first line of _data_ is not present in the output

**Comment by oddodaoddo** [comment]
I concur that there is a problem with skipping the first line. However, I am not sure I understand why.
reader.__next__() is called to get the header line of the file which is assumed to be a .tsv file
if it is indeed a .tsv file, we skip to for row in reader: loop, which should start with the next line (first line of the file with actual data), however, it starts reading at the second line. Do you know why?

Thanks!

**Comment by oddodaoddo** [comment]
Never mind, I can see why (well, I can assume): csv module reads in the header line automatically, as if it is not part of the file. The call to __next__() actually does not read the header line as if it was just any text file with newlines, it reads the first line of the data following it. I wonder if this is documented and I just did not notice it reading the docs for csv module...

**Comment by stolarczyk** [comment]
> reader.next() is called to get the header line of the file which is assumed to be a .tsv file
if it is indeed a .tsv file, we skip to for row in reader: loop, which should start with the next line (first line of the file with actual data), however, it starts reading at the second line

This would be how the `csv.reader` works (first line is the header and then the data rows). 

In case of the `csv.DictReader` the header info is tied to the data rows:

```python
In [2]: with open("index.txt") as tsvfile:
   ...:     reader=csv.reader(tsvfile)
   ...:     for row in reader:
   ...:         print(row)
   ...:         
['filename', 'cellType', 'treatment', 'antibody', 'description']
['GSM1517632_SKNMC.ATACseq.bedGraph', 'SKNMC', 'None', 'None', 'Ewing sarcoma cell line']
['GSM1517633_MSC.empty.ATACseq.bedGraph', 'MSCs', 'None', 'None', 'pLIV empty vector control']
['GSM1517634_MSC.EF.ATACseq.bedGraph', 'MSCs', 'EWS-FLI1', 'None', 'EWS-FLI1 was expressed in MSCs using a lentiviral vector (pLIV EWSFLI1)']

In [3]: with open("index.txt") as tsvfile:
   ...:     reader=csv.DictReader(tsvfile)
   ...:     for row in reader:
   ...:         print(row)
   ...:         
OrderedDict([('filename', 'GSM1517632_SKNMC.ATACseq.bedGraph'), ('cellType', 'SKNMC'), ('treatment', 'None'), ('antibody', 'None'), ('description', 'Ewing sarcoma cell line')])
OrderedDict([('filename', 'GSM1517633_MSC.empty.ATACseq.bedGraph'), ('cellType', 'MSCs'), ('treatment', 'None'), ('antibody', 'None'), ('description', 'pLIV empty vector control')])
OrderedDict([('filename', 'GSM1517634_MSC.EF.ATACseq.bedGraph'), ('cellType', 'MSCs'), ('treatment', 'EWS-FLI1'), ('antibody', 'None'), ('description', 'EWS-FLI1 was expressed in MSCs using a lentiviral vector (pLIV EWSFLI1)')])
```
