### ISSUE TITLE
Misplaced output folder

### ISSUE THREAD

**Issue by joseverdezoto** [databio/bedstat#5]
https://github.com/databio/bedstat/blob/42e76d5da21c3623969d701d977cbf690eece5b3/pipeline/bedstat.py#L35-L44

The pipeline is producing the statistics outputs it's supposed to, but there seems to be an issue with the storage place for the output folder. The folder isn't placed according to the path specified in the output_dir portion of the bedstat_config.yaml file.

**Comment by oddodaoddo** [comment]
Fixed in dev branch. Thanks! :smile:
